### ISSUE TITLE
Building on Ubuntu

### ISSUE THREAD

**Issue by arvids-p** [peterkrenn/lucas-kanade-opencv#1]
When building this on Ubuntu, i get `undefined reference to cvRound`. Then i added `math.h` and changer `cvRound` to `round`.  Now i get `undefined reference to symbol 'round@@GLIBC_2.2.5'` and `x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line`.
Why did you choose Rake to compile?

**Comment by arvids-p** [comment]
Got it to work with openCV version 2.4.13. C code is no longer compatible with openCV 3+.
